site_project/auth_users/urls.py
from django.urls import path, include
from .views import *
# from uchet_active.views import *

app_name = 'auth_users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    #path('', include('uchet_active.urls')), # главная страница, в т.ч. LOGIN_REDIRECT_URL
    # path('reestr_active_list/', reestr_active_list_view, name='reestr_active_list'),

]

site_project/site_project/urls.py
from django.contrib import admin
from django.urls import path, include

from site_project import settings

urlpatterns = [
    
    path('', include('uchet_active.urls')), # главная страница, в т.ч. LOGIN_REDIRECT_URL
    # path('uchet_active/', include('uchet_active.urls')),
    path('admin/', admin.site.urls),    
    path('auth_users/', include('auth_users.urls')),
    path('select2/', include('django_select2.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

site_project/uchet_active/urls.py
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'uchet_active'

urlpatterns = [
    path('', views.index, name='index'),
    # path('', views.name_active_list_view, name='name_active_list_view'),

    # ###########################################################################################################################################################
    # Справочники
    # ###########################################################################################################################################################
    
    # Model Type_active / Тип актива
    path('type_active_list_view/', views.type_active_list_view, name='type_active_list_view'),
    path('type_active/<int:id>/', views.type_active_detail_view, name='type_active_detail_view'),
    path('type_active_create/', views.type_active_create, name='type_active_create'),
    path('type_active_delete/<int:id>/', views.type_active_delete, name='type_active_delete'),
    path('type_active_update/<int:id>/', views.type_active_update, name='type_active_update'),

    # Model Name_active / Модели активов
    path('name_active_list_view/', views.name_active_list_view, name='name_active_list_view'),
    path('name_active/<int:id>/', views.name_active_detail_view, name='name_active_detail_view'),
    path('name_active_create/', views.name_active_create, name='name_active_create'),
    path('name_active_delete/<int:id>/', views.name_active_delete, name='name_active_delete'),
    path('name_active_update/<int:id>/', views.name_active_update, name='name_active_update'),

    # Model Inventory_number / Инвентарные номера
    path('inventory_number_list_view/', views.inventory_number_list_view, name='inventory_number_list_view'),
    path('inventory_number/<int:id>/', views.inventory_number_detail_view, name='inventory_number_detail_view'),
    path('inventory_number_create/', views.inventory_number_create, name='inventory_number_create'),
    path('inventory_number_delete/<int:id>/', views.inventory_number_delete, name='inventory_number_delete'),
    path('inventory_number_update/<int:id>/', views.inventory_number_update, name='inventory_number_update'),

    # Model Owner_active / Владелецы активов
    path('owner_active_list_view/', views.owner_active_list_view, name='owner_active_list_view'),
    path('owner_active/<int:id>/', views.owner_active_detail_view, name='owner_active_detail_view'),
    path('owner_active_create/', views.owner_active_create, name='owner_active_create'),
    path('owner_active_delete/<int:id>/', views.owner_active_delete, name='owner_active_delete'),
    path('owner_active_update/<int:id>/', views.owner_active_update, name='owner_active_update'),

    # Model Location_active / Локация/Склад
    path('location_active_list_view/', views.location_active_list_view, name='location_active_list_view'),
    path('location_active/<int:id>/', views.location_active_detail_view, name='location_active_detail_view'),
    path('location_active_create/', views.location_active_create, name='location_active_create'),
    path('location_active_delete/<int:id>/', views.location_active_delete, name='location_active_delete'),
    path('location_active_update/<int:id>/', views.location_active_update, name='location_active_update'),

    # Model Status_active / Статусы
    path('status_active_list_view/', views.status_active_list_view, name='status_active_list_view'),
    path('status_active/<int:id>/', views.status_active_detail_view, name='status_active_detail_view'),
    path('status_active_create/', views.status_active_create, name='status_active_create'),
    path('status_active_delete/<int:id>/', views.status_active_delete, name='status_active_delete'),
    path('status_active_update/<int:id>/', views.status_active_update, name='status_active_update'),

    # Model Name_quantity_active / Единицы измерения
    path('name_quantity_active_list_view/', views.name_quantity_active_list_view, name='name_quantity_active_list_view'),
    path('name_quantity_active/<int:id>/', views.name_quantity_active_detail_view, name='name_quantity_active_detail_view'),
    path('name_quantity_active_create/', views.name_quantity_active_create, name='name_quantity_active_create'),
    path('name_quantity_active_delete/<int:id>/', views.name_quantity_active_delete, name='name_quantity_active_delete'),
    path('name_quantity_active_update/<int:id>/', views.name_quantity_active_update, name='name_quantity_active_update'),

    # ###########################################################################################################################################################
    # Реестры
    # ###########################################################################################################################################################

    # Model Details_document_active / Реквизиты документов
    path('details_document_active_list_view/', views.details_document_active_list_view, name='details_document_active_list_view'),
    path('details_document_active/<int:id>/', views.details_document_active_detail_view, name='details_document_active_detail_view'),
    path('details_document_active_create/', views.details_document_active_create, name='details_document_active_create'),
    path('details_document_active_delete/<int:id>/', views.details_document_active_delete, name='details_document_active_delete'),
    path('details_document_active_update/<int:id>/', views.details_document_active_update, name='details_document_active_update'),

    # Model Profile_AD / Профили пользователей (AD)
    path('profile_ad_list_view/', views.profile_ad_list_view, name='profile_ad_list_view'),
    path('profile_ad/<int:id>/', views.profile_ad_detail_view, name='profile_ad_detail_view'),
    path('profile_ad_create/', views.profile_ad_create, name='profile_ad_create'),
    path('profile_ad_delete/<int:id>/', views.profile_ad_delete, name='profile_ad_delete'),
    path('profile_ad_update/<int:id>/', views.profile_ad_update, name='profile_ad_update'),

    # Model Receipt_active / Поступление активов
    path('receipt_active_list_view/', views.receipt_active_list_view, name='receipt_active_list_view'),
    path('receipt_active/<int:id>/', views.receipt_active_detail_view, name='receipt_active_detail_view'),
    path('receipt_active_create/', views.receipt_active_create, name='receipt_active_create'),
    path('receipt_active_delete/<int:id>/', views.receipt_active_delete, name='receipt_active_delete'),
    path('receipt_active_update/<int:id>/', views.receipt_active_update, name='receipt_active_update'),

    


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_project/uchet_active/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.http import Http404#, HttpResponse, HttpRequest
from .models import *
from .forms import *
from .filters import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from decouple import config
import ldap
from django.contrib import messages



def index(request):    
    
    title_text = "Index"
    context = {
            'user_login': request.user,
            'title_text':title_text,
        }    
    
    return render(request, 'base.html', context)


# ###########################################################################################################################################################
# Вспомогательные функции
# ###########################################################################################################################################################

# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Получение данных из AD

def select_user_data_ldap(user_name):

    try:
        lconn = ldap.initialize(config("AUTH_LDAP_SERVER_URI"))   # домен
        lconn.protocol_version = ldap.VERSION3  # версия протокола
        lconn.set_option(ldap.OPT_REFERRALS, 0) # не используем рефералы
        lconn.simple_bind_s(config("AUTH_LDAP_BIND_DN"),config("AUTH_LDAP_BIND_PASSWORD"))  # учетные данные
        # print('Connect to AD succesfull')

        base = config("base_find_container")  # начальный контейнер, с которого начинаем поиск объектов
        scope = ldap.SCOPE_SUBTREE  # область поиска, SCOPE_SUBTREE - ищем в дочерних объектах        
        filter = "(&(sAMAccountName=%s))" % user_name  # фильтр, ищем объекты
        attrs = ['displayname','title','mail','sAMAccountName','givenName', 'company', 'extensionAttribute2', 'mobile', 'telephoneNumber']     # атрибуты искомых объектов ('displayname','title','mail','sAMAccountName','givenName')
        
        result_set = []     # массив с полученным результатом
        
        ldap_result_id = lconn.search_ext(base, scope, filter, attrs)   # идентификатор поиска объектов в каталоге

        try:
            while 1:
                result_type, result_data = lconn.result(ldap_result_id, 0)
                if (result_data == []):
                    break
                else:
                    if result_type == ldap.RES_SEARCH_ENTRY:
                        # print("*"*55)
                        # print(result_data)
                        # print("*"*55)

                        fio = result_data[0][0].split(',')[0].split('=')[1] 
                        login = result_data[0][1].get('sAMAccountName')[0].decode("utf-8")
                        mail =  "" if result_data[0][1].get('mail', "") == "" else result_data[0][1].get('mail')[0].decode("utf-8")
                        distinguishedName = result_data[0][0]
                        company = "" if result_data[0][1].get('company', "") == "" else result_data[0][1].get('company')[0].decode("utf-8")
                        company_position = "" if result_data[0][1].get('extensionAttribute2', "") == "" else result_data[0][1].get('extensionAttribute2')[0].decode("utf-8")
                        mobile = "" if result_data[0][1].get('mobile', "") == "" else result_data[0][1].get('mobile')[0].decode("utf-8")
                        telephoneNumber = "" if result_data[0][1].get('telephoneNumber', "") == "" else result_data[0][1].get('telephoneNumber')[0].decode("utf-8")
                        
                        result_set.append({"fio":fio, "login":login, "mail":mail, "distinguishedName":distinguishedName,
                                            "company":company, "company_position":company_position,
                                            "mobile":mobile, "telephoneNumber":telephoneNumber,})

        except ldap.SIZELIMIT_EXCEEDED:
            print("ldap.SIZELIMIT_EXCEEDED")

        # for item in result_set:
        #     print(item)        
        return result_set     # массив с полученным результатом
    
    except ldap.SERVER_DOWN:
        print('Error connection to AD')


# ###########################################################################################################################################################
# Справочники
# ###########################################################################################################################################################


# ***********************************************************************************************************************************************************
# Model Type_active / Типы активов


# # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# @login_required
# @permission_required(perm='uchet_active.view_type_active', raise_exception=True)
# def type_active_list_view(request):
#     dataset = Type_active.objects.all() # Получаем все записи
#     count_dataset = dataset.count()

#     page = request.GET.get('page', 1)
#     paginator = Paginator(dataset, 10)  #  paginate_by 10
#     try:
#         dataset = paginator.page(page)
#     except PageNotAnInteger:
#         dataset = paginator.page(1)
#     except EmptyPage:
#         dataset = paginator.page(paginator.num_pages) 

#     title_text = "Типы активов (список записей)"
#     context = {
#             # 'user_login': request.user,            
#             'dataset': dataset,      
#             'count_dataset': count_dataset,      
#             'title_text':title_text,
#             'user_group_admin': config("USER_GROUP_ADMIN"),  
#             'user_group_staf': config("USER_GROUP_STAF"),
#             'url_delete_view': 'uchet_active:type_active_delete',
#             'url_update_view': 'uchet_active:type_active_update',          
#         }    
#     return render(request, 'uchet_active/type_active_listview.html', context)


# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@login_required
@permission_required(perm='uchet_active.view_type_active', raise_exception=True)
def type_active_list_view(request):
    dataset = Type_active.objects.all() # Получаем все записи
    dataset_filter = Type_active_Filter(request.GET, queryset=dataset)

    count_dataset = dataset_filter.qs.count()

    dataset = dataset_filter.qs
    paginator = Paginator(dataset, 10)  #  paginate_by 10
    page_number = request.GET.get('page')
    
    try:
        dataset = paginator.page(page_number)
    except PageNotAnInteger:
        dataset = paginator.page(1)
    except EmptyPage:
        dataset = paginator.page(paginator.num_pages) 

    title_text = "Типы активов (список записей)"
    context = {
            # 'user_login': request.user,
            'filter': dataset_filter,
            'dataset': dataset,      
            'count_dataset': count_dataset,      
            'title_text':title_text,
            'user_group_admin': config("USER_GROUP_ADMIN"),  
            'user_group_staf': config("USER_GROUP_STAF"),
            'url_delete_view': 'uchet_active:type_active_delete',
            'url_update_view': 'uchet_active:type_active_update',
            'url_return_to_the_list_view': 'uchet_active:type_active_list_view',
        }    
    return render(request, 'uchet_active/type_active_listview.html', context)


# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@login_required
@permission_required(perm='uchet_active.view_type_active', raise_exception=True)
def type_active_detail_view(request, id):
    try:
        # Получаем запись по-определенному id
        data = Type_active.objects.get(id=id)
        title_text = "Тип актива"
        context = {
            'data': data,      
            'title_text':title_text,
            'url_return_to_the_list_view': 'uchet_active:type_active_list_view',
            'user_group_admin': config("USER_GROUP_ADMIN"),  
            'user_group_staf': config("USER_GROUP_STAF"),
            'url_delete_view': 'uchet_active:type_active_delete',
            'url_update_view': 'uchet_active:type_active_update',
        }
    except Type_active.DoesNotExist:
        raise Http404('Такой записи не существует') 
    return render(request, 'uchet_active/type_active_detailview.html', context)


# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@login_required
@permission_required(perm='uchet_active.add_type_active', raise_exception=True)    
def type_active_create(request):
    title_text = "Тип актива (добавление записи)"
    # Проверяем, что запрос на добавление записи (POST) или просто на получение формы
    if request.method == 'POST':
        # Получаем из запроса только те данные которые использует форма
        form = Type_active_Form(request.POST)
        # Проверяем правильность введенных данных
        if form.is_valid():
            # сохраняем в базу
            form.save()
            # переадресуем на listview
            return redirect('uchet_active:type_active_list_view')
    else:
        form =Type_active_Form()
    context = {
            # 'user_login': request.user,
            'form': form,
            'title_text': title_text,
            'url_return_to_the_list_view': 'uchet_active:type_active_list_view',  
            'user_group_admin': config("USER_GROUP_ADMIN"),  
            'user_group_staf': config("USER_GROUP_STAF"),          
        }        
    return render(request, 'uchet_active/create.html', context)


# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@login_required
@permission_required(perm='uchet_active.change_type_active', raise_exception=True)
def type_active_update(request, id):
    try:
        old_data = get_object_or_404(Type_active, id=id)
        title_text = "Тип актива (обновление записи)"
    except Exception:
        raise Http404('Такой записи не существует')
    
    # Если метод POST, то это обновленные данные
    # Остальные методы - возврат данных для изменения
    if request.method =='POST':
        form = Type_active_Form(request.POST, instance=old_data)
        if form.is_valid():
            form.save()

site_project/uchet_active/templates/base.html
<!doctype html>
<html lang="en" data-bs-theme="light">
  <head>
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  
    <title>{% block title %}{% endblock title %}</title>

    <style>  
      .title_text {
        text-align: center; 
        font-size: 2.0em;
        font-weight: bold;
      }  

      .title_table {
            text-align: center; 
            font-size: 2.0em;
        } 

      .idClass {
          white-spce: nowrap;
          width: 1%; /* Форсирует сужение ячейки */
        }

      .navbar-toggler {
        border-color: black;
        background-color: white;
      }  
      
      

      
      

    </style>



    {% comment %} select2 lnk {% endcomment %}
    <link href="/static/css/select2.min.css" rel="stylesheet" />
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" /> {% endcomment %}

    
</head>
  <body>

    

    {% if request.user.is_authenticated %}

      <main class="container-fluid bg-body-tertiary rounded">      
        <nav class="navbar navbar-expand-lg bg-primary">
          <div class="container-fluid">
            <a class="navbar-brand text-light" href="#">Главный реестр</a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>            
            <div class="collapse navbar-collapse" id="navbarScroll">
              <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Справочники</a>
                  <ul class="dropdown-menu">                    
                    <li><a class="dropdown-item" href="{% url 'uchet_active:type_active_list_view' %}">Типы активов</a></li>                    
                    <li><a class="dropdown-item" href="{% url 'uchet_active:name_active_list_view' %}">Модели активов</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'uchet_active:inventory_number_list_view' %}">Инвентарные номера</a></li>
                    <li><a class="dropdown-item" href="{% url 'uchet_active:name_quantity_active_list_view' %}">Единицы измерения</a></li>
                    <li><a class="dropdown-item" href="{% url 'uchet_active:status_active_list_view' %}">Статусы</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'uchet_active:owner_active_list_view' %}">Владелецы активов</a></li>
                    <li><a class="dropdown-item" href="{% url 'uchet_active:location_active_list_view' %}">Локация/Склад</a></li>
                    <li><hr class="dropdown-divider"></li>
                    
                  </ul>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Реестры</a>
                  <ul class="dropdown-menu">                    
                    <li><a class="dropdown-item" href="{% url 'uchet_active:details_document_active_list_view' %}">Реквизиты документов</a></li>                    
                    {% comment %} <li><a class="dropdown-item" href="{% url 'uchet_active:name_active_list_view' %}">Модели активов</a></li> {% endcomment %}
                    <li><hr class="dropdown-divider"></li>
                    
                    <li><a class="dropdown-item" href="{% url 'uchet_active:profile_ad_list_view' %}">Профили пользователей (AD)</a></li>
                    <li><hr class="dropdown-divider"></li>

                    <li><a class="dropdown-item" href="{% url 'uchet_active:receipt_active_list_view' %}">Поступление активов</a></li>
                    <li><hr class="dropdown-divider"></li>
                    
                  </ul>
                </li>

                {% comment %} 
                <li class="nav-item">
                  <a class="nav-link active text-light" aria-current="page" href="#">Home</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link text-light" href="#">Link</a>
                </li>                

                <li class="nav-item">
                  <a class="nav-link disabled" aria-disabled="true">Link</a>
                </li> 
                {% endcomment %}
                
              </ul>

              {% comment %} <a class="navbar-brand px-3" href="#"></a>

              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-md btn-secondary" type="submit" style="border-color: white;">Найти</button>                
              </form> {% endcomment %}

              <a class="navbar-brand px-5" href="#"></a>

              <form class="d-flex">
                <a class="navbar-brand text-light d-flex" href="#">Пользователь: {{request.user}}</a>
                <a class="btn btn-md btn-secondary" href="{% url 'auth_users:logout' %}" role="button" style="border-color: white;">Выход</a>
                {% comment %} <a class="navbar-brand text-light d-flex" href="{% url 'auth_users:logout' %}">[выход]</a> {% endcomment %}
              </form>

            </div>
          </div>
        </nav>
      </main>

      {% comment %} <main class="container-fluid bg-body-tertiary p-5 rounded"> {% endcomment %}
      <main class="container-fluid bg-body-tertiary rounded">
          {% comment %} <div class="container-fluid text-center fs-1 fw-bold my-3 py-1" style="position:sticky; top:0px;"> {% endcomment %}
          <div class="container-fluid">
              <div class="title_text">
                {% block header %}{% endblock header %}
              </div>            
          </div>
          
          <div class="container-fluid">
              {% block body %}{% endblock body %}
          </div>
          
      </main>      

    {% else %}
      <main class="container-fluid bg-body-tertiary rounded">
        <div class="container-fluid">          
          <div class="title_text">  
            <header>Ошибка авторизации</header>
          </div>      
          <div class="container-fluid">          
            <h2>Вы не авторизированы</h2>              
          </div>
          <div class="container-fluid">            
            <a class="btn btn-lg btn-primary" href="{% url 'auth_users:login' %}" role="button">Нажмите для входа в систему &raquo;</a>            
          </div>
        </div>
      </main>
    {% endif %}
    
    
    <script src="/static/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    {% comment %} select2 lnk {% endcomment %}    
    <script src="/static/js/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    {% comment %} <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script> {% endcomment %}
    <script src="/static/js/select2.min.js"></script>
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script> {% endcomment %}

    <div class="container-fluid ">
      {% block scripts %}
      
      {% endblock scripts %}
    </div>
  </body>
</html>