site_project/auth_users/urls.py
from django.urls import path, include
from .views import *
# from uchet_active.views import *

app_name = 'auth_users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    #path('', include('uchet_active.urls')), # главная страница, в т.ч. LOGIN_REDIRECT_URL
    # path('reestr_active_list/', reestr_active_list_view, name='reestr_active_list'),

]

site_project/site_project/urls.py
from django.contrib import admin
from django.urls import path, include

from site_project import settings

urlpatterns = [
    
    path('', include('uchet_active.urls')), # главная страница, в т.ч. LOGIN_REDIRECT_URL
    # path('uchet_active/', include('uchet_active.urls')),
    path('admin/', admin.site.urls),    
    path('auth_users/', include('auth_users.urls')),
    path('select2/', include('django_select2.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

site_project/uchet_active/urls.py
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'uchet_active'

urlpatterns = [
    path('', views.index, name='index'),
    # path('', views.name_active_list_view, name='name_active_list_view'),

    # ###########################################################################################################################################################
    # Справочники
    # ###########################################################################################################################################################
    
    # Model Type_active / Тип актива
    path('type_active_list_view/', views.type_active_list_view, name='type_active_list_view'),
    path('type_active/<int:id>/', views.type_active_detail_view, name='type_active_detail_view'),
    path('type_active_create/', views.type_active_create, name='type_active_create'),
    path('type_active_delete/<int:id>/', views.type_active_delete, name='type_active_delete'),
    path('type_active_update/<int:id>/', views.type_active_update, name='type_active_update'),

    # Model Name_active / Модели активов
    path('name_active_list_view/', views.name_active_list_view, name='name_active_list_view'),
    path('name_active/<int:id>/', views.name_active_detail_view, name='name_active_detail_view'),
    path('name_active_create/', views.name_active_create, name='name_active_create'),
    path('name_active_delete/<int:id>/', views.name_active_delete, name='name_active_delete'),
    path('name_active_update/<int:id>/', views.name_active_update, name='name_active_update'),

    # Model Inventory_number / Инвентарные номера
    path('inventory_number_list_view/', views.inventory_number_list_view, name='inventory_number_list_view'),
    path('inventory_number/<int:id>/', views.inventory_number_detail_view, name='inventory_number_detail_view'),
    path('inventory_number_create/', views.inventory_number_create, name='inventory_number_create'),
    path('inventory_number_delete/<int:id>/', views.inventory_number_delete, name='inventory_number_delete'),
    path('inventory_number_update/<int:id>/', views.inventory_number_update, name='inventory_number_update'),

    # Model Owner_active / Владелецы активов
    path('owner_active_list_view/', views.owner_active_list_view, name='owner_active_list_view'),
    path('owner_active/<int:id>/', views.owner_active_detail_view, name='owner_active_detail_view'),
    path('owner_active_create/', views.owner_active_create, name='owner_active_create'),
    path('owner_active_delete/<int:id>/', views.owner_active_delete, name='owner_active_delete'),
    path('owner_active_update/<int:id>/', views.owner_active_update, name='owner_active_update'),

    # Model Location_active / Локация/Склад
    path('location_active_list_view/', views.location_active_list_view, name='location_active_list_view'),
    path('location_active/<int:id>/', views.location_active_detail_view, name='location_active_detail_view'),
    path('location_active_create/', views.location_active_create, name='location_active_create'),
    path('location_active_delete/<int:id>/', views.location_active_delete, name='location_active_delete'),
    path('location_active_update/<int:id>/', views.location_active_update, name='location_active_update'),

    # Model Status_active / Статусы
    path('status_active_list_view/', views.status_active_list_view, name='status_active_list_view'),
    path('status_active/<int:id>/', views.status_active_detail_view, name='status_active_detail_view'),
    path('status_active_create/', views.status_active_create, name='status_active_create'),
    path('status_active_delete/<int:id>/', views.status_active_delete, name='status_active_delete'),
    path('status_active_update/<int:id>/', views.status_active_update, name='status_active_update'),

    # Model Name_quantity_active / Единицы измерения
    path('name_quantity_active_list_view/', views.name_quantity_active_list_view, name='name_quantity_active_list_view'),
    path('name_quantity_active/<int:id>/', views.name_quantity_active_detail_view, name='name_quantity_active_detail_view'),
    path('name_quantity_active_create/', views.name_quantity_active_create, name='name_quantity_active_create'),
    path('name_quantity_active_delete/<int:id>/', views.name_quantity_active_delete, name='name_quantity_active_delete'),
    path('name_quantity_active_update/<int:id>/', views.name_quantity_active_update, name='name_quantity_active_update'),

    # ###########################################################################################################################################################
    # Реестры
    # ###########################################################################################################################################################

    # Model Details_document_active / Реквизиты документов
    path('details_document_active_list_view/', views.details_document_active_list_view, name='details_document_active_list_view'),
    path('details_document_active/<int:id>/', views.details_document_active_detail_view, name='details_document_active_detail_view'),
    path('details_document_active_create/', views.details_document_active_create, name='details_document_active_create'),
    path('details_document_active_delete/<int:id>/', views.details_document_active_delete, name='details_document_active_delete'),
    path('details_document_active_update/<int:id>/', views.details_document_active_update, name='details_document_active_update'),

    # Model Profile_AD / Профили пользователей (AD)
    path('profile_ad_list_view/', views.profile_ad_list_view, name='profile_ad_list_view'),
    path('profile_ad/<int:id>/', views.profile_ad_detail_view, name='profile_ad_detail_view'),
    path('profile_ad_create/', views.profile_ad_create, name='profile_ad_create'),
    path('profile_ad_delete/<int:id>/', views.profile_ad_delete, name='profile_ad_delete'),
    path('profile_ad_update/<int:id>/', views.profile_ad_update, name='profile_ad_update'),

    # Model Receipt_active / Поступление активов
    path('receipt_active_list_view/', views.receipt_active_list_view, name='receipt_active_list_view'),
    path('receipt_active/<int:id>/', views.receipt_active_detail_view, name='receipt_active_detail_view'),
    path('receipt_active_create/', views.receipt_active_create, name='receipt_active_create'),
    path('receipt_active_delete/<int:id>/', views.receipt_active_delete, name='receipt_active_delete'),
    path('receipt_active_update/<int:id>/', views.receipt_active_update, name='receipt_active_update'),

    


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_project/uchet_active/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.validators import MinValueValidator


# ###########################################################################################################################################################
# Справочники
# ###########################################################################################################################################################

class Type_active(models.Model):
    type_active = models.CharField(max_length=50, verbose_name='Тип актива', unique=True, db_index=True)    
    
    class Meta:
        # db_table='Type_active' # указание имени таблицы в базе данных "вручную"
        verbose_name_plural = '(1.1) Типы активов'
        verbose_name = 'Тип актива'
        ordering = ['type_active',]
    
    def __str__(self):
        return f"{self.type_active}"
    
    def get_absolute_url(self):
        return reverse('uchet_active:type_active_detail_view', args=[self.id,])


class Name_active(models.Model):
    type_active = models.ForeignKey('Type_active', on_delete=models.PROTECT, verbose_name='Тип актива')
    manufacturer = models.CharField(max_length=50, verbose_name='Производитель', db_index=True)
    name_model = models.CharField(max_length=50, verbose_name='Модель', db_index=True)
    
    class Meta:
        verbose_name_plural = '(1.2) Модели активов'
        verbose_name = 'Модель актива'
        ordering = ['type_active', 'manufacturer', 'name_model']
    
    def __str__(self):        
        return f"{self.type_active.type_active} {self.manufacturer} {self.name_model}"
    
    def get_absolute_url(self):
        return reverse('uchet_active:name_active_detail_view', args=[self.id,])


class Inventory_number(models.Model):
    inventory_number = models.CharField(max_length=50, verbose_name='Инвентарный номер', unique=True, db_index=True)
    
    class Meta:
        verbose_name_plural = '(1.3) Инвентарные номера'
        verbose_name = 'Инвентарный номер'
        ordering = ['inventory_number',]

    def __str__(self):
        return f"{self.inventory_number}"
    
    def get_absolute_url(self):
        return reverse('uchet_active:inventory_number_detail_view', args=[self.id,])


class Name_quantity_active(models.Model):
    name_quantity = models.CharField(max_length=25, verbose_name='Ед.изм-я', unique=True, db_index=True)   
    
    class Meta:        
        verbose_name_plural = '(1.4) Единицы измерения'
        verbose_name = 'Единица измерения'
        ordering = ['name_quantity',]
    
    def __str__(self):
        return f"{self.name_quantity}"
    
    def get_absolute_url(self):
        return reverse('uchet_active:name_quantity_active_detail_view', args=[self.id,])


class Status_active(models.Model):
    status = models.CharField(max_length=25, verbose_name='Статус', unique=True, db_index=True)   
    
    class Meta:        
        verbose_name_plural = '(1.5) Статусы'
        verbose_name = 'Статус'
        ordering = ['status',]
    
    def __str__(self):
        return f"{self.status}"
    
    def get_absolute_url(self):
        return reverse('uchet_active:status_active_detail_view', args=[self.id,])


class Owner_active(models.Model):
    owner_active = models.CharField(max_length=150, verbose_name='Владелец актива', unique=True, db_index=True)
    
    class Meta:
        verbose_name_plural = '(1.6) Владелецы активов'
        verbose_name = 'Владелец актива'
        ordering = ['owner_active',]
    
    def __str__(self):
        return f"{self.owner_active}"
    
    def get_absolute_url(self):
        return reverse('uchet_active:owner_active_detail_view', args=[self.id,])


class Location_active(models.Model):
    owner_active = models.ForeignKey('Owner_active', on_delete=models.PROTECT, verbose_name='Владелец актива')
    location = models.CharField(max_length=150, verbose_name='Локация/Склад', db_index=True)           
    
    class Meta:        
        verbose_name_plural = '(1.7) Локация/Склад'
        verbose_name = 'Локация/Склад'
        ordering = ['owner_active','location',]
    
    def __str__(self):
        return f"{self.owner_active}, {self.location}"
    
    def get_absolute_url(self):
        return reverse('uchet_active:location_active_detail_view', args=[self.id,])



# ###########################################################################################################################################################
# Реестры
# ###########################################################################################################################################################

class Details_document_active(models.Model):
    name_document = models.CharField(max_length=50, verbose_name='Документ', db_index=True)
    shipping_location = models.CharField(max_length=150, verbose_name='Локация/Склад отгрузки', db_index=True)
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи', db_index=True)    
    creator_account = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, verbose_name='Кем изменено/создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')    
    
    class Meta:        
        verbose_name_plural = '(2.1) Реквизиты документов'
        verbose_name = 'Реквизиты документа'
        ordering = ['name_document','shipping_location',]
    
    def __str__(self):
        return f"{self.name_document}"
    
    def get_absolute_url(self):
        return reverse('uchet_active:details_document_active_detail_view', args=[self.id,])


class Profile_AD(models.Model):
    account = models.CharField(max_length=50, verbose_name='Учетная запись', db_index=True)
    fio = models.CharField(max_length=75, verbose_name='ФИО')
    email = models.EmailField(verbose_name='Email')
    distingished_name = models.CharField(max_length=175, verbose_name='Имя объекта')
    company = models.CharField(max_length=75, blank=True, verbose_name='Юридическое лицо')
    company_position = models.CharField(max_length=100, blank=True, verbose_name='Должность')
    mobile = models.CharField(max_length=35, blank=True, verbose_name='Телефон (мобильный)')
    telephone_number = models.CharField(max_length=35, blank=True, verbose_name='Телефон')

    class Meta:        
        verbose_name_plural = '(2.2) Профили пользователей (AD)'
        verbose_name = 'Профиль пользователя (AD)'
        ordering = ['account',]
    
    def __str__(self):
        return f"{self.account}"
    
    def get_absolute_url(self):
        return reverse('uchet_active:profile_ad_detail_view', args=[self.id,])


class Receipt_active(models.Model):
    details_document_active = models.ForeignKey('Details_document_active', on_delete=models.PROTECT, verbose_name='Реквизиты документа')
    inventory_number = models.ForeignKey('Inventory_number', on_delete=models.PROTECT, verbose_name='Инвентарный номер')
    name_active = models.ForeignKey('Name_active', on_delete=models.PROTECT, verbose_name='Модель актива')
    location_active = models.ForeignKey('Location_active', on_delete=models.PROTECT, verbose_name='Локация/Склад')
    name_quantity_active = models.ForeignKey('Name_quantity_active', on_delete=models.PROTECT, verbose_name='Ед.изм-я')
    quantity = models.IntegerField(verbose_name='Количество', default=1, validators=[MinValueValidator(1),])
    serial_number = models.CharField(max_length=50, blank=True, verbose_name='S/N')
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи', db_index=True)    
    creator_account = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, verbose_name='Кем изменено/создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')    
    
    class Meta:        
        verbose_name_plural = '(2.3) Поступление активов'
        verbose_name = 'Поступление актива'
        ordering = ['created',]
    
    def __str__(self):
        return f"{self.inventory_number} {str(self.name_active)} ({self.quantity} {self.name_quantity_active.name_quantity})"
    
    def get_absolute_url(self):
        return reverse('uchet_active:receipt_active_detail_view', args=[self.id,])

site_project/uchet_active/templates/uchet_active/details_document_active_delete.html
{% extends "uchet_active/delete.html" %}

{% block table %}
    <table class="table table-striped table-hover table-bordered border-primary text-center">
        <thead class="table-primary">
            <tr>
                <th class="idClass" scope="col">id</th>
                <th scope="col">Документ</th>
                <th scope="col">Локация/Склад отгрузки</th>
                <th scope="col">comment</th>
                <th scope="col">Дата создания</th>
                <th scope="col">Кем изменено/создано</th>
                <th scope="col">Дата изменения</th>
            </tr>
        </thead>
        <tbody>                    
            <tr>
                <th class="idClass" scope="row">{{ data.id }}</th>
                <td>{{ data.name_document  }}</td>
                <td>{{ data.shipping_location }}</td>
                <td>{{ data.comment }}</td>
                <td>{{ data.created }}</td>
                <td>{{ data.creator_account }}</td>
                <td>{{ data.updated }}</td>
            </tr>                    
        </tbody>
    </table>         
{% endblock table %}

site_project/uchet_active/templates/uchet_active/details_document_active_detailview.html
{% extends "uchet_active/detailview.html" %}
{% load has_group %}

{% block table %}
        <table class="table table-striped table-hover table-bordered border-primary text-center">
            <thead class="table-primary">
                <tr>
                    <th class="idClass" scope="col">id</th>
                    <th scope="col">Документ</th>
                    <th scope="col">Локация/Склад отгрузки</th>
                    <th scope="col">comment</th>
                    <th scope="col">Дата создания</th>
                    <th scope="col">Кем изменено/создано</th>
                    <th scope="col">Дата изменения</th>

                    {% if request.user|has_group:user_group_admin or request.user|has_group:user_group_staf %}
                        <th scope="col">Операции над записью</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>                    
                <tr>
                    <th class="idClass" scope="row">{{ data.id }}</th>
                    <td>{{ data.name_document  }}</td>
                    <td>{{ data.shipping_location }}</td>
                    <td>{{ data.comment }}</td>
                    <td>{{ data.created }}</td>
                    <td>{{ data.creator_account }}</td>
                    <td>{{ data.updated }}</td>

                    {% if request.user|has_group:user_group_admin or request.user|has_group:user_group_staf %}
                        <td>
                            <a class="btn btn-sm btn-warning" href="{% url url_update_view id=data.id %}">Изменить</a>
                            <a class="btn btn-sm btn-danger" href="{% url url_delete_view id=data.id %}">Удалить</a>
                        </td>
                    {% endif %}
                </tr>                    
            </tbody>
        </table>        
{% endblock table %}

site_project/uchet_active/templates/uchet_active/messages.html
{% for message in messages %}
    <div class="container-fluid">
        <div class="alert {{message.tags}} alert-dismissible" role="alert">
            {% comment %} <button type="button" class="close" data-dimiss="alert" aria-label="close">
            <span aria-hidden="true">x</span>
            </button> {% endcomment %}
            {{message}}
        </div>
    </div>
{% endfor %}

site_project/uchet_active/templates/uchet_active/name_quantity_active_listview.html
{% extends "uchet_active/listview.html" %}
{% load has_group %}
{% load widget_tweaks %}


{% block buttons %}
    {% if request.user|has_group:user_group_admin or request.user|has_group:user_group_staf %}

        <div class="row mx-auto my-1 my-sm-1 my-lg-1 p-1">
            <div class="col-3 align-self-center">
                <a class="btn btn-sm btn-success" href="{% url 'uchet_active:name_quantity_active_create' %}" role="button">Добавить новую запись</a>
            </div>
            
        </div>

    {% endif %}    
{% endblock buttons %}

{% block table %}
            <table class="table table-striped table-hover table-bordered border-primary text-center">
                <thead class="table-primary">
                    {% comment %} <tr class="title_table"><th colspan="2">{{ title_text }}, [всего: {{ count_dataset }}]</th></tr> {% endcomment %}
                    <tr>
                        <th class="idClass" scope="col">id (ссылка)</th>
                        <th scope="col">Единица измерения</th>
                        
                        {% comment %} {% if request.user|has_group:user_group_admin or request.user|has_group:user_group_staf %} {% endcomment %}
                            <th scope="col">Операции над записями</th>
                        {% comment %} {% endif %} {% endcomment %}
                    </tr>
                </thead>
                <thead class="table-secondary">
                    <tr>
                        <form method="GET" action="" class="form-inline"><!-- class="popup" -->
                            {% csrf_token %}
                            <th>
                                {% comment %} <div class="row" style="margin: 3px;">
                                    {% render_field filter.form.id   %}
                                </div> {% endcomment %}
                            </th>        
                            <th>
                                <div class="row mx-auto" >
                                    {% render_field filter.form.name_quantity   class="form-conrol" %}<!--  -->
                                </div>
                            </th>                            
                            <th>
                                <button type="submit" class="btn btn-sm btn-info" >Фильтровать</button>
                                <a class="btn btn-sm btn-secondary" href="{% url url_return_to_the_list_view %}" role="button">Очистить</a>                                
                            </th>                            
                        </form>
                    </tr>
                </thead>
                <tbody>
                    {% for data in dataset %}
                        <tr>
                            <th class="idClass" scope="row">
                                <div class="d-grid gap-2">
                                    <a class="btn btn-sm btn-outline-primary" href="{{ data.get_absolute_url }}" role="button">{{ data.id }}</a>
                                </div>
                            </th>
                            <td>{{ data.name_quantity}}</td>

                            {% if request.user|has_group:user_group_admin or request.user|has_group:user_group_staf %}
                                <td>
                                    <a class="btn btn-sm btn-warning" href="{% url url_update_view id=data.id %}">Изменить</a>
                                    <a class="btn btn-sm btn-danger" href="{% url url_delete_view id=data.id %}">Удалить</a>
                                </td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        </tr>                    
                    {% endfor %}
                </tbody>
            </table>
{% endblock table %}

site_project/uchet_active/templates/uchet_active/receipt_active_listview.html
{% extends "uchet_active/listview.html" %}
{% load has_group %}
{% load widget_tweaks %}


{% block buttons %}
    {% if request.user|has_group:user_group_admin or request.user|has_group:user_group_staf %}

        <div class="row mx-auto my-1 my-sm-1 my-lg-1 p-1">
            <div class="col-3 align-self-center">
                <a class="btn btn-sm btn-success" href="{% url 'uchet_active:receipt_active_create' %}" role="button">Добавить новую запись</a>
            </div>
            
        </div>

    {% endif %}    
{% endblock buttons %}

{% block table %}
            <table class="table table-striped table-hover table-bordered border-primary text-center">
                <thead class="table-primary">
                    {% comment %} <tr class="title_table"><th colspan="4">{{ title_text }}, [всего: {{ count_dataset }}]</th></tr> {% endcomment %}
                    <tr>
                        <th class="idClass" scope="col">id (ссылка)</th>
                        <th scope="col">Реквизиты документа (ссылка)</th>
                        <th scope="col">Инвентарный номер (ссылка)</th>
                        <th scope="col">Модель актива (ссылка)</th>
                        <th scope="col">Локация/Склад (ссылка)</th>
                        <th scope="col">Количество</th>
                        <th scope="col">Ед.изм-я (ссылка)</th>                        
                        <th scope="col">S/N</th>
                        <th scope="col">Комментарий</th>
                        <th scope="col">Дата создания</th>
                        <th scope="col">Кем изменено/создано</th>
                        <th scope="col">Дата изменения</th>
                        
                        {% comment %} {% if request.user|has_group:user_group_admin or request.user|has_group:user_group_staf %} {% endcomment %}
                            <th scope="col">Операции над записями</th>
                        {% comment %} {% endif %} {% endcomment %}
                    </tr>
                </thead>
                <thead class="table-secondary">
                    <tr>
                        <form method="GET" action="" class="form-inline"><!-- class="popup" -->
                            {% csrf_token %}
                            <th>{% comment %} <div class="row mx-auto" > {% render_field filter.form.id   %} </div> {% endcomment %}</th>       
                            <th> {% render_field filter.form.details_document_active   class="form-conrol" %} </th>
                            <th> {% render_field filter.form.inventory_number   class="form-conrol" %} </th>
                            <th> {% render_field filter.form.name_active   class="form-conrol" %} </th>
                            <th> {% render_field filter.form.location_active   class="form-conrol" %} </th>
                            <th> <div class="row mx-auto" > {% render_field filter.form.quantity   class="form-conrol" %} </div> </th>
                            <th> {% render_field filter.form.name_quantity_active   class="form-conrol" %} </th>                            
                            <th> <div class="row mx-auto" > {% render_field filter.form.serial_number   class="form-conrol" %} </div> </th>
                            <th> <div class="row mx-auto" > {% render_field filter.form.comment   class="form-conrol" %} </div> </th>
                            <th> <div class="row mx-auto" > {% render_field filter.form.created   class="form-conrol" %} </div> </th>
                            <th> {% render_field filter.form.creator_account   class="form-conrol" %} </th>
                            <th> <div class="row mx-auto" > {% render_field filter.form.updated   class="form-conrol" %} </div> </th>
                            
                            <th>
                                <button type="submit" class="btn btn-sm btn-info" >Фильтровать</button>
                                <a class="btn btn-sm btn-secondary" href="{% url url_return_to_the_list_view %}" role="button">Очистить</a>                                
                            </th>                            
                        </form>
                    </tr>
                </thead>
                <tbody>
                    {% for data in dataset %}
                    <tr>
                        <th class="idClass" scope="row">
                            <div class="d-grid gap-2">
                                <a class="btn btn-sm btn-outline-primary" href="{{ data.get_absolute_url }}" role="button">{{ data.id }}</a>
                            </div>
                        </th>
                        <td>
                            <div class="d-grid gap-2">
                                <a class="btn btn-sm btn-outline-primary" href="{{ data.details_document_active.get_absolute_url }}" role="button">{{ data.details_document_active }}</a>
                            </div>
                        </td>
                        <td>
                            <div class="d-grid gap-2">
                                <a class="btn btn-sm btn-outline-primary" href="{{ data.inventory_number.get_absolute_url }}" role="button">{{ data.inventory_number }}</a>
                            </div>
                        </td>
                        <td>
                            <div class="d-grid gap-2">
                                <a class="btn btn-sm btn-outline-primary" href="{{ data.name_active.get_absolute_url }}" role="button">{{ data.name_active }}</a>
                            </div>
                        </td>
                        <td>
                            <div class="d-grid gap-2">
                                <a class="btn btn-sm btn-outline-primary" href="{{ data.location_active.get_absolute_url }}" role="button">{{ data.location_active }}</a>
                            </div>
                        </td>
                        <td>{{ data.quantity }}</td>
                        <td>
                            <div class="d-grid gap-2">
                                <a class="btn btn-sm btn-outline-primary" href="{{ data.name_quantity_active.get_absolute_url }}" role="button">{{ data.name_quantity_active }}</a>
                            </div>
                        </td>                            
                        <td>{{ data.serial_number }}</td>
                        <td>{{ data.comment }}</td>
                        <td>{{ data.created }}</td>
                        <td>{{ data.creator_account }}</td>
                        <td>{{ data.updated }}</td>
    
                        {% if request.user|has_group:user_group_admin or request.user|has_group:user_group_staf %}
                            <td>
                                <a class="btn btn-sm btn-warning" href="{% url url_update_view id=data.id %}">Изменить</a>
                                <a class="btn btn-sm btn-danger" href="{% url url_delete_view id=data.id %}">Удалить</a>
                            </td>
                        {% else %}
                            <td></td>
                        {% endif %}
                    </tr>                    
                    {% endfor %}
                </tbody>
            </table>
{% endblock table %}

{% block scripts %}
<script>    
    $("#id_details_document_active").select2({ width:'100%'});
    $("#id_inventory_number").select2({ width:'100%'});
    $("#id_name_active").select2({ width:'100%'});
    $("#id_location_active").select2({ width:'100%'});
    $("#id_name_quantity_active").select2({ width:'100%'});
    $("#id_creator_account").select2({ width:'100%'});
    $("#id_owner_active").select2({ width:'100%'});
    $("#id_type_active").select2({ width:'100%'});    
</script>
{% endblock scripts %}